const sauce = [
    {name:'ポーク', price:514, default: true},
    {name:'ポーク甘口', price:514, spiciness: false},
    {name:'ビーフ', price:641},
    {name:'ココイチベジソース', price:641},
    {name:'ハッシュドビーフ', price:641},
];

const spiciness = [
    {name:'0', price:0, default: true},
    {name:'1', price:22},
    {name:'2', price:44},
    {name:'3', price:66},
    {name:'4', price:88},
    {name:'5', price:110},
];

const sweetness = [
    {name:'0', price:0, default: true},
    {name:'1', price:22},
    {name:'2', price:44},
    {name:'3', price:66},
    {name:'4', price:88},
    {name:'5', price:110},
];

// TODO タグ付け
const toppings = [
    {name:'クリーミータルタルソース', price:52},
    {name:'ガーリック', price:52},
    {name:'半熟タマゴ', price:73},
    {name:'ゆでタマゴ', price:73},
    {name:'赤たまねぎのピクルス', price:82},
    {name:'単品ポテト', price:105},
    {name:'ツナ', price:105},
    {name:'コーン', price:105},
    {name:'オクラ山芋', price:105},
    {name:'半熟タマゴタルタルソース', price:125},
    {name:'なす', price:157},
    {name:'納豆', price:157},
    {name:'フィッシュフライ', price:157},
    {name:'スクランブルエッグ', price:157},
    {name:'大豆ミートのメンチカツ', price:157},
    {name:'たっぷりあさり', price:189},
    {name:'エビあさり', price:199},
    {name:'２個カキフライ', price:199},
    {name:'イカ', price:206},
    {name:'クリームコロッケ(カニ入り)', price:206},
    {name:'エビにこみ', price:206},
    {name:'きのこ', price:206},
    {name:'チーズ', price:221},
    {name:'やさい', price:226},
    {name:'ほうれん草', price:226},
    {name:'チキンにこみ', price:243},
    {name:'フライドチキン', price:243},
    {name:'ハンバーグ', price:262},
    {name:'豚しゃぶ', price:262},
    {name:'メンチカツ', price:262},
    {name:'ロースカツ', price:295},
    {name:'チキンカツ', price:295},
    {name:'パリパリチキン', price:295},
    {name:'ソーセージ', price:295},
    {name:'海の幸', price:304},
    {name:'スタミナポークレバー', price:343},
    {name:'ビーフカツ', price:367},
    {name:'カキフライ（４個）', price:398},
    {name:'エビカツ', price:440},
    {name:'手仕込とんかつ', price:471},
    {name:'手仕込豚ヒレ勝つ', price:482},
];
